name: Bug Report
description: File a bug report.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshot"
      description: If applicable, add a screenshot(s) to help explain your problem.
      placeholder: "Click inside and drag and drop an image here..."
    validations:
      required: false
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: In which package(s) of the library is the issue occurring?
      options:
        # default is 'None'
        - 'All'
        - 'Styles'
        - 'Angular'
        - 'Icons'
        - 'Not applicable'
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the package are you running?
      placeholder: "eg. 1.1.0"
    validations:
      required: true
  - type: input
    id: repro-url
    attributes:
      label: "Reproduction URL"
      description: Please enter a URL for the Storybook where the bug can be reproduced, a URL to a fork of https://codesandbox.io/p/github/ekateriinal/angular-cvi-starter or a public link to a minimal reproduction of your own
      placeholder: "eg. https://e-gov.github.io/cvi/?path=/story/angular-form-input--default"
    validations:
      required: false
  - type: input
    id: browser
    attributes:
      label: Browser
      description: If applicable, what browser are you seeing the problem on?
      placeholder: Chrome
    validations:
      required: false
  - type: input
    id: browser-version
    attributes:
      label: Browser version
      description: If applicable, what browser version are you seeing the problem on?
      placeholder: "112"
    validations:
      required: false
  - type: textarea
    id: extra-environment-info
    attributes:
      label: Extra details about your environment
      description: If applicable, provide extra details on your environment.
      placeholder: |
        Node: 14.17.0
        Package Manager: npm 8
        OS: linux x64
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks
      render: shell
  - type: markdown
    attributes:
      value: |
        I confirm by submitting this issue that I have studied the [README file](https://github.com/e-gov/cvi/blob/main/README.md), read the [Storybook documentation](https://e-gov.github.io/cvi/?path=/story/intro--page) and, if applicable, attempted to reproduce it.
