export type IconName =
  | 'call'
  | 'email'
  | 'arrow-a-left'
  | 'arrow-a-right'
  | 'library-add'
  | 'location'
  | 'screen-share'
  | 'happy-face'
  | 'sad-face'
  | 'light-bulb'
  | 'warning-amber'
  | 'error-outline'
  | 'check-circle-outline'
  | 'info'
  | 'close';
