#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

branch_name="$(git rev-parse --abbrev-ref HEAD)"
branch_pattern="^(feature|fix|test){1}-[[:upper:]]{2,4}-[[:digit:]]{3,4}-[a-zA-Z0-9.-]+$"

if [[ ! $branch_name =~ $branch_pattern ]];
then
  echo "---"
  echo "Violation of branch naming convention!"
  echo "The branch name must have following formatting:"
  echo "<feature/fix/test>-<JIRA-TASK-NUMBER>-<description>"
  echo "Example: feature-STPA-035-branch-hook"
  echo "For more information, check script in .husky/pre-push"
  echo "---"
  exit 1
fi
